#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changedFiles="$(git diff --name-only --cached)"

yarn spell-check --files ${changedFiles} "!public/**" "!**/*.css" "!**/*.lock" "!**/*.json" "!node_modules/*" "!next/*" "!.env**"
yarn check-types
yarn lint-staged